folder_original: /home/mantis/test
folder_in: /home/mantis/test/tst
folder_out: /home/mantis/test/out
folder_ext: /home/mantis/test/folder1
folder_ext2: /home/mantis/test/folder2
files_count: 10
bs: 1M
arx_name: arx3
arx_type: zip
log_txt: stat.txt